### PR TITLE
Add CF integration tests and test fixtures for RC2

### PR DESCRIPTION
**Pull request by RochesterinNYC**
- These integration specs successfully ran on PCFDev, CF `v237` running DEAs, CF `v237` running Diego, and CF `v225` running DEAs.

Tracker Story: https://www.pivotaltracker.com/story/show/119907003

### CODE REVIEW

**Comment by opiethehokie** [comment]
This is awesome! Thanks for updating for RC2.

**Comment by opiethehokie** [comment]
Would you mind adding the cf_spec directory to the exclude_files section in manifest.yml as part of this? And maybe the visual studio files and project.lock.json files don't need to be in the fixtures, but it's certainly valid to push an app like that, so I don't have too strong of an opinion either way.

**Comment by RochesterinNYC** [comment]
Ah, good call. Made those changes. Yup, I don't think the visual studio or project.lock.json files are necessary. Cheers.

**Comment by degrim** [comment]
It looks like there are still a few extra files hanging around in there:

    cf_spec/fixtures/asp_mvc_app/wwwroot/images/ASP-NET-Banners-01.png
    cf_spec/fixtures/asp_web_app/.vscode/*

Other than that, it looks good.

**Pull request merged**
