### PR TITLE
Add offline compatibility for cached version of buildpack

### PR DESCRIPTION
**Pull request by RochesterinNYC**
- This new integration spec testing that the buildpack does not call out to the internet (along with existing integration specs) successfully ran on PCFDev, CF v237 running DEAs, CF v237 running Diego, and CF v225 running DEAs.
- Added dotnet dependency to manifest
- Use compile-extensions for getting dotnet
- Also added buildpack cache support for dotnet (dotnet will not try to download and reinstall/untar each buildpack run on the same app)

Tracker Story: https://www.pivotaltracker.com/story/show/119946447

### CODE REVIEW

**Comment by RochesterinNYC** [comment]
As a side note, we noticed that this method (`#libunwind_tar_gz`) is not being utilized anywhere. https://github.com/cloudfoundry-community/dotnet-core-buildpack/blob/master/lib/buildpack/compile/libunwind_installer.rb#L32-L34

Should it be removed?

**Comment by degrim** [comment]
Adding the dotnet cli to manifest.yml like that takes away the ability to support newer versions as they are released.  This seems like a regression of the functionality we previously had with DNX which allowed users to pull the latest toolchain as soon as it was publicly released without any updates to the buildpack.

**Comment by RochesterinNYC** [comment]
Are there Cloud Foundry use cases where users would want their dotnet runtime to be the latest/not locked with each push? I don't have the context on how CF users are using/deploying dotnet apps at the moment, so please help me understand some of the use cases here. It feels odd to me that a user could push their dotnet app repeatedly with the same buildpack version but get a different runtime at some point (if the dotnet CLI has an update released during this process).

**Comment by RochesterinNYC** [comment]
Additionally, is the concern here providing the latest versions in a timely manner or the fact that new releases would be required to do so?

The first can be mitigated by watching for new versions of the dependencies, the second is more of a general buildpack design/intention concern.

**Comment by degrim** [comment]
In the past, this buildpack has allowed the user to specify which version of the runtime their application would use by specifying it in the global.json file and newer versions of the runtime were always made available when Microsoft released it.  Making a new release every time a new runtime is released without including any other changes in the release doesn't make sense to me because it would make users wait longer to use new releases of the runtime without any real reason to justify that extra waiting period.  When users develop applications using Visual Studio, the global.json file specifies which runtime version is used to compile and run the application and this behavior should be the same in the buildpack.

**Comment by opiethehokie** [comment]
@RochesterinNYC I think I was using the method (#libunwind_tar_gz) to test finding the dependency in the manifest without actually downloading it. Maybe it's pointless since it's not even calling the same compile-extensions script. Is there a better way to do that? Or you think it's not needed?

**Comment by RochesterinNYC** [comment]
I think the `#libunwind_tar_gz` method is no longer needed due to the usage of `compile-extensions/bin/download_dependency` in the `#extract` method.

**Comment by RochesterinNYC** [comment]
@degrim thanks for that context. So if that behavior was kept intact, a way that this buildpack could run in an offline/disconnected environment is if we implement the following behavior/details:

- We package/specify a few of the latest dotnet runtimes via the manifest
- If running in an online env, the buildpack can download any runtime.
- If running in an offline env, if the global.json specifies a runtime that is not packaged as a dependency and is not present in the manifest, then the buildpack can error out and warn appropriately. if the specified runtime is packaged and present in the manfiest, it can grab that runtime from the dependencies cache.

However, I don't believe there is currently a canonical way for a buildpack to know whether it is a cached or uncached version (whether it's supposed to run offline or not)? There are approximations that you can make (ex. detecting whether there are dependencies/files in the `dependencies` directory), but these might not be something to rely on.

**Comment by degrim** [comment]
Any project being pushed as source code requires the .Net CLI to be installed would need to restore packages from nuget.org as well.  To make the buildpack truly "offline" in that scenario you would also have to cache all 616,981 packages from nuget.org.  The only other scenario which requires the .Net CLI to be installed is when the user publishes an application as a portable application which requires the .Net CLI to run.  In this scenario, the application can be modified to be a "self-contained" application which would include all of the required files with the published application and would not require the buildpack to download anything but libunwind.

**Comment by RochesterinNYC** [comment]
Gotcha. The use case for offline buildpacks is usually with those types of self-contained applications (ex. the fixture app in this PR). If the application was not self-contained and required pulling packages from nuget.org, then it would not be used with the offline version of a buildpack.

The second scenario is the one that would be nice to support with an offline buildpack. Essentially enabling the pushing of a self-contained app with an offline/cached buildpack that has dotnet and libunwind in the manifest/dependency cache without hitting the internet at all.

**Comment by degrim** [comment]
A self-contained app will not require the .Net CLI to be pre-installed, nor will it download the .Net CLI with the current buildpack.

**Comment by opiethehokie** [comment]
OK lets remove the `#libunwind_tar_gz method` then.

**Comment by opiethehokie** [comment]
To make sure we're all on the same page, this is a good reference on self-contained vs. portable apps I was just reading - [http://dotnet.github.io/docs/core-concepts/app-types.html]()

So self-contained apps don't need the buildpack to provide the CLI, but I see that as mostly separate from the manifest discussion. I do like the idea of getting the dotnet dependency into the manifest. Then with the cached version of the buildpack a portable app would also work offline it seems. I guess that's what @degrim is saying it looks like is happening here. 

I think I'm onboard with @RochesterinNYC 's latest ideas:

> * We package/specify a few of the latest dotnet runtimes via the manifest
* If running in an online env, the buildpack can download any runtime.

The default if there's nothing in global.json would be the newest version from the cache so it's guaranteed to be compatible with the buildpack?

> However, I don't believe there is currently a canonical way for a buildpack to know whether it is a cached or uncached version (whether it's supposed to run offline or not)? There are approximations that you can make (ex. detecting whether there are dependencies/files in the dependencies directory), but these might not be something to rely on.

Does it make sense to try a http request to find out if you're offline or online?

**Comment by opiethehokie** [comment]
After thinking this over for a few days I'm not exactly sure what to do about adding the dotnet dependency to the manifest, partly because it's not yet clear how it will be updated post-RTM. I think we can agree that it's still a good idea to have an offline test though. Can this pull request be updated to be just for a self-contained app (which should work offline now) and then the manifest work can be done separately?

**Comment by RochesterinNYC** [comment]
@opiethehokie @degrim I'm in accordance here. I think a lot more discussion/thought is needed to determine what a truly offline dotnet buildpack (that will not try to hit the internet or make any http requests) would look like.

We'll change this PR to just be the inclusion of the self-contained app fixture for the integration specs. I don't believe it'll truly work offline (not try to hit the internet or make any http requests at all) though.

**Comment by degrim** [comment]
@RochesterinNYC So long as the app is self-contained and not portable, it will not download the .NET CLI.  It should only need the libunwind dependency which can be cached with the buildpack in that case.

**Comment by jbogenschneider** [comment]
I did a ubuntu 14.4 self contained (to the best of my knowledge) build with RC2 and get this error from cli client when pushing to PCF.  I get it from Linux cli and Mac

mkeloxmr45gfd57:BuildPackTest jbogenschneider$ cf push dotnettestapi -b https://github.com/cloudfoundry-community/dotnet-core-buildpack.git
Updating app dotnettestapi in org Corelogic / space sb as jbogenschneider@corelogic.com...
OK

Uploading dotnettestapi...
Uploading app files from: /users/jbogenschneider/documents/docker/BuildPackTest
Uploading 49.9M, 180 files
Done uploading               
OK

Starting app dotnettestapi in org .......
Creating container
Successfully created container
Downloading app package...
Downloaded app package (20.6M)
Staging...
ASP.NET Core buildpack version: 0.8.0
ASP.NET Core buildpack starting compile
-----> Restoring files from buildpack cache
       OK
-----> Extracting libunwind
       libunwind version: 1.1
       /usr/lib/ruby/2.2.0/digest.rb:49:in `initialize': No such file or directory @ rb_sysopen - /tmp/libunwind-x-1.1.tar.gz (Errno::ENOENT)
       	from /usr/lib/ruby/2.2.0/digest.rb:49:in `open'
       	from /usr/lib/ruby/2.2.0/digest.rb:49:in `file'
       	from /usr/lib/ruby/2.2.0/digest.rb:34:in `file'
       	from /tmp/buildpacks/63d5a1e25de8205658beee5d2f0c1aa0/compile-extensions/bin/download_dependency:30:in `<main>'
       FAILED: command failed, exit status 1
       FAILED: Extracting libunwind failed, command failed, exit status 1
Failed to compile droplet
Exit status 223
Staging failed: Exited with status 223

FAILED
BuildpackCompileFailed

**Comment by degrim** [comment]
@jbogenschneider Could you open an issue for that, and also include the project.json and project structure of your application please.

**Comment by degrim** [comment]
Given that Microsoft didn't add the preview2 build of the tools to the same stream that the preview1 tools were in, we'll need to add the .NET CLI to the manifest.yml now to make the buildpack compatible with the new tooling build.  I think we should be good to merge this PR as-is in that case and then update the manifest.yml to both include the new tooling build and use a CDN to download the preview1 build rather than the azure blob storage location that it currently downloads the tooling from which has been very slow over the last few days.

**Pull request merged**
